import subprocess
import re
import os
from Bio.PDB import PDBParser
import numpy as np


# ------------------------------------------------
# Convert WSL path → Windows path for Vina
# ------------------------------------------------

def linux_to_windows_path(path: str):
    return path.replace("/mnt/d", "D:").replace("/", "\\")


# ------------------------------------------------
# Compute docking center from active site residues
# ------------------------------------------------

def compute_active_site_center(protein_pdb, active_sites):

    parser = PDBParser(QUIET=True)
    structure = parser.get_structure("protein", protein_pdb)

    coords = []

    for site in active_sites:

        chain_id = site["chain_id"]
        res_num = site["residue_number"]

        try:
            residue = structure[0][chain_id][(" ", res_num, " ")]
        except KeyError:
            continue

        for atom in residue.get_atoms():
            coords.append(atom.coord)

    if not coords:
        raise RuntimeError("Active site atoms not found in protein")

    coords = np.array(coords)
    center = coords.mean(axis=0)

    return center


# ------------------------------------------------
# Run AutoDock Vina
# ------------------------------------------------

def run_vina(receptor, ligand, active_sites, top_n=3):

    vina_path = "/mnt/d/Major project/vina/vina_1.2.7_win.exe"

    output_dir = "data/docking_results"
    os.makedirs(output_dir, exist_ok=True)

    docked_pdbqt = os.path.join(output_dir, "docked_output.pdbqt")

    # ------------------------------------------------
    # Compute docking center from active site
    # ------------------------------------------------

    center = compute_active_site_center(receptor, active_sites)

    center_x, center_y, center_z = center

    print("Docking center:", center_x, center_y, center_z)

    # ------------------------------------------------
    # Convert paths for Windows executable
    # ------------------------------------------------

    receptor_win = linux_to_windows_path(receptor)
    ligand_win = linux_to_windows_path(ligand)
    output_win = linux_to_windows_path(docked_pdbqt)

    # ------------------------------------------------
    # Run Vina
    # ------------------------------------------------

    cmd = [
        vina_path,
        "--receptor", receptor_win,
        "--ligand", ligand_win,
        "--center_x", str(center_x),
        "--center_y", str(center_y),
        "--center_z", str(center_z),
        "--size_x", "20",
        "--size_y", "20",
        "--size_z", "20",
        "--exhaustiveness", "8",
        "--seed", "42",
        "--cpu", "0",
        "--out", output_win
    ]

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
    )

    print("\n------ VINA STDOUT ------\n")
    print(result.stdout)

    print("\n------ VINA STDERR ------\n")
    print(result.stderr)

    if not os.path.exists(docked_pdbqt):
        raise RuntimeError("Docking output not generated by Vina")

    output = result.stdout

    # ------------------------------------------------
    # Parse docking results
    # ------------------------------------------------

    poses = []

    for line in output.splitlines():

        match = re.match(r"\s*(\d+)\s+(-?\d+\.\d+)", line)

        if match:
            mode = int(match.group(1))
            affinity = float(match.group(2))

            poses.append({
                "mode": mode,
                "affinity": affinity
            })

    if not poses:
        raise RuntimeError("Failed to parse docking results")

    poses = sorted(poses, key=lambda x: x["affinity"])
    top_poses = poses[:top_n]

    # ------------------------------------------------
    # Split poses into PDB files
    # ------------------------------------------------

    subprocess.run([
        "obabel",
        docked_pdbqt,
        "-O",
        os.path.join(output_dir, "pose_.pdb"),
        "-m"
    ])

    pose_files = []

    for i, pose in enumerate(top_poses):

        pose_file = os.path.join(output_dir, f"pose_{i+1}.pdb")

        if not os.path.exists(pose_file):
            raise RuntimeError(f"Pose file missing: {pose_file}")

        pose_files.append({
            "mode": pose["mode"],
            "affinity": pose["affinity"],
            "structure_file": pose_file
        })

    best_affinity = pose_files[0]["affinity"]

    return {
        "best_affinity": best_affinity,
        "top_poses": pose_files,
        "raw_output": output
    }