import subprocess
import re
import os


def linux_to_windows_path(path: str):
    return path.replace("/mnt/d", "D:").replace("/", "\\")


def run_vina(receptor, ligand, top_n=3):

    vina_path = "/mnt/d/Major project/vina/vina_1.2.7_win.exe"

    output_dir = "/mnt/d/Major project/Source code/docking_results"
    os.makedirs(output_dir, exist_ok=True)

    docked_pdbqt = os.path.join(output_dir, "docked_output.pdbqt")

    receptor_win = linux_to_windows_path(receptor)
    ligand_win = linux_to_windows_path(ligand)
    output_win = linux_to_windows_path(docked_pdbqt)

    # ------------------------------------------------
    # Run Vina
    # ------------------------------------------------

    cmd = [
        vina_path,
        "--receptor", receptor_win,
        "--ligand", ligand_win,
        "--center_x", "15",
        "--center_y", "15",
        "--center_z", "15",
        "--size_x", "20",
        "--size_y", "20",
        "--size_z", "20",
        "--exhaustiveness", "8",
        "--seed", "42",
        "--cpu", "0",
        "--out", output_win
    ]

    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        timeout=120
    )

    print("\n------ VINA STDOUT ------\n")
    print(result.stdout)

    print("\n------ VINA STDERR ------\n")
    print(result.stderr)

    output = result.stdout

    if not os.path.exists(docked_pdbqt):
        raise RuntimeError("Docking output not generated by Vina")

    # ------------------------------------------------
    # Parse docking table
    # ------------------------------------------------

    poses = []

    for line in output.splitlines():

        match = re.match(r"\s*(\d+)\s+(-?\d+\.\d+)", line)

        if match:
            mode = int(match.group(1))
            affinity = float(match.group(2))

            poses.append({
                "mode": mode,
                "affinity": affinity
            })

    if not poses:
        raise RuntimeError("Failed to parse docking results")

    poses = sorted(poses, key=lambda x: x["affinity"])

    top_poses = poses[:top_n]

    # ------------------------------------------------
    # Split poses
    # ------------------------------------------------

    subprocess.run([
        "obabel",
        docked_pdbqt,
        "-O",
        os.path.join(output_dir, "pose_.pdb"),
        "-m"
    ])

    pose_files = []

    for i, pose in enumerate(top_poses):

        pose_file = os.path.join(output_dir, f"pose_{i+1}.pdb")

        if not os.path.exists(pose_file):
            raise RuntimeError(f"Pose file missing: {pose_file}")

        pose_files.append({
            "mode": pose["mode"],
            "affinity": pose["affinity"],
            "structure_file": pose_file
        })

    best_affinity = pose_files[0]["affinity"]

    return {
        "best_affinity": best_affinity,
        "top_poses": pose_files,
        "raw_output": output
    }